const genres = [
    { text: 'Podcast', image_alt: '#DE4C8A', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDDrNJbrCbb2xQ4V2XNz90wAR5wT_gr2Di0w&usqp=CAU'},
    { text: 'Pop', image_alt: '#78858B', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbfbCXm4eKWKmcaXo2sXE2Y_kj26Qdj2yMHA&usqp=CAU'},
    { text: 'Hip-Hop', image_alt: '#4A192C', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9CDJoNp6ZH08TVU5qWeusNTIST5JOqUvAVQ&usqp=CAU'},
    { text: 'Rock', image_alt: '#6C7156',  image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlpbmydn9rNQR9NGQY5GMN-pVvNqccbnoeJg&usqp=CAU'},
    { text: 'Latino', image_alt: '#212121',  image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgqRW0UvPVNZ6sAJ-xxgVeEN3lbsVNYPDC1g&usqp=CAU'},
    { text: 'Dance', image_alt: '#D36E70', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLBi7KXZGT6VEtyymOuHJC-l7WBrlvz9gRAA&usqp=CAU'},
    { text: 'Best Mode', image_alt: '#2D572C', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTeI-g61abbnp8fhJkA3urh0jnCmDUZuTREg&usqp=CAU'},
    { text: 'Indie', image_alt: '#84C3BE', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuA-wPCBMcJ-kv5OJ6o4y0H8Unr-Mzbx6mdA&usqp=CAU'},
    { text: 'Discover', image_alt: '#CFD3CD', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHMdMlT1nJXBmpG6iTEm-fXcjbzsQrQ2nToQ&usqp=CAU'},
    { text: 'Country', image_alt: '#5E2129', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWnAB4910lNeK6KAY0wZlYHKJJPdvNb4pxHA&usqp=CAU'},
    { text: 'Stand Up', image_alt: '#C93C20', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSshbx1AhUaUQwG6ga4FsoFe-i743_4KNHPqQ&usqp=CAU'},
    { text: 'K-Pop', image_alt: '#641C34', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCffu2rNVylPg-VcP30R5_mbiJ_pqhloB_5MdmCeENDR2YnooJhkfrDa7eg1sYhdF14mo&usqp=CAU'},
    { text: 'Relaxation', image_alt: '#343E40', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuCMnMVKXIIbfrL1JpEtwTXrX3GaAkN3Yk8Q&usqp=CAU'},
    { text: 'Bedtime', image_alt: '#89AC76', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMCqgto-5aNmnZrJS14Zpv9hWyp_zpn7JVHQ&usqp=CAU'},
    { text: 'Party', image_alt: '#5E2129sed', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2u8yvvrAQTo44WJ2r003slw5IjF9i_k7yqw&usqp=CAU'},
    { text: 'Home', image_alt: '#F54021', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT05oj55beXCCpdPj2Lcd34qUR1vSD5SMWUXQ&usqp=CAU'},
    { text: 'Romantic', image_alt: '#F39F18', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyGeOBWUNCiNIsDGaH3VC84NNoptF-znemWA&usqp=CAU'},
    { text: 'Metal', image_alt: '#464531', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEIQyWpXfciA1tPGTE-CzMvKo5iqKfSe33FA&usqp=CAU'},
    { text: 'Clasic', image_alt: '#434B4D', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgRN0LeCqmbcMpK2TVKUrzKfUs5S9VzDrodw&usqp=CAU'},
    { text: 'Acoustic Folk', image_alt: '#3B83BD', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRg4s1bnssv7VjAsGw6jDZTnItogY8-Jr7Kbw&usqp=CAU'},
    { text: 'Concentration', image_alt: '#6C6960',image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfZQL-a1nZ9F5H0Ak9zmGsClSZAupRBYqX-w&usqp=CAU'},
    { text: 'Soul', image_alt: '#592321', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOpmGLsR5jEo9lE6eaRRK-77vfsCydaZtv1g&usqp=CAU'},
    { text: 'Ambient', image_alt: '#FFA420', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUAtatSjKKjBYfwrZIaHOR7qiocKbzA_xwFA&usqp=CAU'},
    { text: 'Blues', image_alt: '#D53032', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbC8DyRCv59E-5GUzBFjbjCh3Kunv2MvUCxQ&usqp=CAU'},
    { text: 'Caraibe', image_alt: '#C7B446',image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMMLfFqe8QxOpinDNPqQBeIuS2DcIZL_NCYA&usqp=CAU'},
    { text: 'Afro', image_alt: '#CBD0CC', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdMGPLGaNVO_Xmkn1u1yAWH-sRtvMbLTL2bA&usqp=CAU'},
    { text: 'EQUAL', image_alt: '#2F353B', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBJvHtrfLg7rhmEk_0wh89KgFFYSbHRgDn_Q&usqp=CAU'},
    { text: 'Summer', image_alt: '#7F7679', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROV222KpGOwDVoeKc5YanZyfrDg-77mF4Q9g&usqp=CAU'},
    { text: 'Freqency', image_alt: '#C6A664', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMcT-pr_mbPcOBViAuKf_jOGemCRlJV4O12g&usqp=CAU'},
    { text: 'Fresh Finds', image_alt: '#1E1E1E',image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4UI-0EcznkCifRUHwa4cqx9ufp2CD3HvpYA&usqp=CAU'},
    { text: 'Good Feeling', image_alt: '#382C1E', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhAqLDkc_DjLrzP595gDRU6EHS5iTWV8-ing&usqp=CAU'},
    { text: 'RADAR', image_alt: '#5E2129', image_src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRowu3Yggv-lkPwhHJAITSmUQ8K9QgolyU23A&usqp=CAU'},
]
export default genres;
